services:
# Ubuntu containers
  source:
    non_xr: true
    image: alpine:3.15
    container_name: source
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    command: /bin/sh -c "ip route add 10.0.0.0/8 via 10.0.25.1 && /bin/sh"
    networks:
      source-xrd-25:
        ipv4_address: 10.0.25.2

# XRd containers
  xrd-25:
    xr_startup_cfg: config/xrd25.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Gi0/0/0/4
      - Mg0/RP0/CPU0/0
        #    networks:
        #source-xrd-25:
        #ipv4_address: 10.0.25.1
  xrd-26:
    xr_startup_cfg: config/xrd26.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Gi0/0/0/4
      - Gi0/0/0/5
      - Mg0/RP0/CPU0/0
  xrd-27:
    xr_startup_cfg: config/xrd27.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Gi0/0/0/4
      - Gi0/0/0/5
      - Mg0/RP0/CPU0/0
  xrd-28:
    xr_startup_cfg: config/xrd28.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd-29:
    xr_startup_cfg: config/xrd29.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd-30:
    xr_startup_cfg: config/xrd30.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

xr_l2networks:
  - ["xrd-25:Gi0/0/0/0", "xrd-26:Gi0/0/0/2"]
  - ["xrd-25:Gi0/0/0/4", "xrd-28:Gi0/0/0/3"]
  - ["xrd-25:Gi0/0/0/1", "xrd-30:Gi0/0/0/0"]
  - ["xrd-26:Gi0/0/0/0", "xrd-28:Gi0/0/0/0"]
  - ["xrd-27:Gi0/0/0/0", "xrd-28:Gi0/0/0/1"]
  - ["xrd-27:Gi0/0/0/1", "xrd-29:Gi0/0/0/1"]
  - ["xrd-28:Gi0/0/0/2", "xrd-29:Gi0/0/0/0"]
  - ["xrd-30:Gi0/0/0/2", "xrd-26:Gi0/0/0/1"]
  - ["xrd-30:Gi0/0/0/1", "xrd-27:Gi0/0/0/2"]

networks:
  mgmt:
    xr_interfaces:
      - xrd-27:Mg0/RP0/CPU0/0
      - xrd-25:Mg0/RP0/CPU0/0
      - xrd-26:Mg0/RP0/CPU0/0
      - xrd-28:Mg0/RP0/CPU0/0
      - xrd-29:Mg0/RP0/CPU0/0
      - xrd-30:Mg0/RP0/CPU0/0
    ipam:
      config:
        - subnet: 172.40.0.0/24
  source-xrd-25:
    ipam:
      config:
        - subnet: 10.0.25.0/24
    xr_interfaces:
      - xrd-25:Gi0/0/0/2
  xrd-29-host:
    ipam:
      config:
        - subnet: 10.10.29.0/24
    xr_interfaces:
      - xrd-29:Gi0/0/0/2