services:
# Ubuntu containers
  source:
    non_xr: true
    image: alpine:3.15
    container_name: alpine-06
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    command: /bin/sh -c "ip route add 10.0.0.0/8 via 10.10.6.2 && /bin/sh"
    networks:
      xrd06-host:
        ipv4_address: 10.10.6.4

# XRd containers
  xrd00:
    xr_startup_cfg: config/xrd00.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd01:
    xr_startup_cfg: config/xrd01.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd02:
    xr_startup_cfg: config/xrd02.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Gi0/0/0/4
      - Gi0/0/0/5
      - Gi0/0/0/6
      - Mg0/RP0/CPU0/0
  xrd03:
    xr_startup_cfg: config/xrd03.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Gi0/0/0/4
      - Gi0/0/0/5
      - Gi0/0/0/6
      - Mg0/RP0/CPU0/0

  xrd04:
    xr_startup_cfg: config/xrd04.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd05:
    xr_startup_cfg: config/xrd05.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd06:
    xr_startup_cfg: config/xrd06.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Mg0/RP0/CPU0/0

  xrd07:
    xr_startup_cfg: config/xrd07.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Gi0/0/0/4
      - Mg0/RP0/CPU0/0
  xrd08:
    xr_startup_cfg: config/xrd08.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Gi0/0/0/4
      - Mg0/RP0/CPU0/0

  xrd09:
    xr_startup_cfg: config/xrd09.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd10:
    xr_startup_cfg: config/xrd10.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

 

xr_l2networks:
  - ["xrd00:Gi0/0/0/0", "xrd02:Gi0/0/0/6"]
  - ["xrd00:Gi0/0/0/1", "xrd03:Gi0/0/0/6"]

  - ["xrd01:Gi0/0/0/0", "xrd02:Gi0/0/0/5"]
  - ["xrd01:Gi0/0/0/1", "xrd03:Gi0/0/0/5"] 

  - ["xrd02:Gi0/0/0/0", "xrd03:Gi0/0/0/0"]

  - ["xrd02:Gi0/0/0/2", "xrd04:Gi0/0/0/2"]


  - ["xrd03:Gi0/0/0/1", "xrd05:Gi0/0/0/2"]
 

  - ["xrd04:Gi0/0/0/0", "xrd05:Gi0/0/0/0"]
  - ["xrd04:Gi0/0/0/1", "xrd08:Gi0/0/0/4"]
  - ["xrd04:Gi0/0/0/3", "xrd06:Gi0/0/0/1"]

  - ["xrd05:Gi0/0/0/1", "xrd07:Gi0/0/0/2"]
  - ["xrd05:Gi0/0/0/3", "xrd06:Gi0/0/0/0"]

  - ["xrd07:Gi0/0/0/0", "xrd08:Gi0/0/0/0"]

  - ["xrd07:Gi0/0/0/3", "xrd10:Gi0/0/0/0"]
  - ["xrd07:Gi0/0/0/4", "xrd09:Gi0/0/0/0"]

  - ["xrd08:Gi0/0/0/1", "xrd09:Gi0/0/0/1"]
  - ["xrd08:Gi0/0/0/2", "xrd10:Gi0/0/0/1"]



networks:
  mgmt:
    xr_interfaces:
      - xrd00:Mg0/RP0/CPU0/0
      - xrd01:Mg0/RP0/CPU0/0
      - xrd02:Mg0/RP0/CPU0/0
      - xrd03:Mg0/RP0/CPU0/0
      - xrd04:Mg0/RP0/CPU0/0
      - xrd05:Mg0/RP0/CPU0/0
      - xrd06:Mg0/RP0/CPU0/0
      - xrd07:Mg0/RP0/CPU0/0
      - xrd08:Mg0/RP0/CPU0/0
      - xrd09:Mg0/RP0/CPU0/0
      - xrd10:Mg0/RP0/CPU0/0
    ipam:
      config:
        - subnet: 10.251.254.0/24

  xrd00-host1:
    ipam:
      config:
        - subnet: 10.1.41.0/29
    xr_interfaces:
      - xrd00:Gi0/0/0/2
  xrd00-host2:
    ipam:
      config:
        - subnet: 10.1.40.0/29
    xr_interfaces:
      - xrd00:Gi0/0/0/3

  xrd01-host1:
    ipam:
      config:
        - subnet: 10.1.41.8/29
    xr_interfaces:
      - xrd01:Gi0/0/0/2
  xrd01-host2:
    ipam:
      config:
        - subnet: 10.1.40.8/29
    xr_interfaces:
      - xrd01:Gi0/0/0/3

  xrd06-host:
    ipam:
      config:
        - subnet: 10.10.6.0/24
    xr_interfaces:
      - xrd06:Gi0/0/0/2

  xrd09-host1:
    ipam:
      config:
        - subnet: 10.10.51.0/29
    xr_interfaces:
      - xrd09:Gi0/0/0/2
  xrd09-host2:
    ipam:
      config:
        - subnet: 10.10.50.0/29
    xr_interfaces:
      - xrd09:Gi0/0/0/3

  xrd10-host1:
    ipam:
      config:
        - subnet: 10.10.51.8/29
    xr_interfaces:
      - xrd10:Gi0/0/0/2
  xrd10-host2:
    ipam:
      config:
        - subnet: 10.10.50.8/29
    xr_interfaces:
      - xrd10:Gi0/0/0/3






