services:
# Ubuntu containers
  source:
    non_xr: true
    image: alpine:3.15
    container_name: source
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    command: /bin/sh -c "ip route add 10.0.0.0/8 via 10.0.25.1 && /bin/sh"
    networks:
      source-xrd-25:
        ipv4_address: 10.0.25.2

# XRd
  xrd-31:
    xr_startup_cfg: config/xrd31.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd-32:
    xr_startup_cfg: config/xrd32.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd-33:
    xr_startup_cfg: config/xrd33.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd-34:
    xr_startup_cfg: config/xrd34.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0


xr_l2networks:
  - ["xrd-31:Gi0/0/0/0", "xrd-32:Gi0/0/0/0"]
  - ["xrd-31:Gi0/0/0/1", "xrd-33:Gi0/0/0/2"]
  - ["xrd-32:Gi0/0/0/2", "xrd-34:Gi0/0/0/0"]
  - ["xrd-33:Gi0/0/0/1", "xrd-34:Gi0/0/0/1"]


networks:
  mgmt:
    xr_interfaces:
      - xrd-31:Mg0/RP0/CPU0/0
      - xrd-32:Mg0/RP0/CPU0/0
      - xrd-33:Mg0/RP0/CPU0/0
      - xrd-34:Mg0/RP0/CPU0/0

    ipam:
      config:
        - subnet: 172.40.0.0/24
  source-xrd-25:
    ipam:
      config:
        - subnet: 10.0.25.0/24
    xr_interfaces:
      - xrd-31:Gi0/0/0/2
  xrd-29-host:
    ipam:
      config:
        - subnet: 10.10.29.0/24
    xr_interfaces:
      - xrd-34:Gi0/0/0/2