# The 6-node topology is comprised of routers xrd25 thru xrd30

services:
# Ubuntu containers
  source:
    non_xr: true
    image: alpine:3.15
    container_name: source
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    command: /bin/sh -c "ip route add 10.0.0.0/8 via 10.0.25.1 && /bin/sh"
    networks:
      source-xrd25:
        ipv4_address: 10.0.25.2

# XRd containers
  xrd25:
    xr_startup_cfg: config/xrd25.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Gi0/0/0/4
      - Mg0/RP0/CPU0/0
        #    networks:
        #source-xrd25:
        #ipv4_address: 10.0.25.1
  xrd26:
    xr_startup_cfg: config/xrd26.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Gi0/0/0/4
      - Gi0/0/0/5
      - Mg0/RP0/CPU0/0
  xrd27:
    xr_startup_cfg: config/xrd27.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Gi0/0/0/4
      - Gi0/0/0/5
      - Mg0/RP0/CPU0/0
  xrd28:
    xr_startup_cfg: config/xrd28.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd29:
    xr_startup_cfg: config/xrd29.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd30:
    xr_startup_cfg: config/xrd30.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

xr_l2networks:
  - ["xrd25:Gi0/0/0/0", "xrd26:Gi0/0/0/2"]
  - ["xrd25:Gi0/0/0/4", "xrd28:Gi0/0/0/3"]
  - ["xrd25:Gi0/0/0/1", "xrd30:Gi0/0/0/0"]
  - ["xrd26:Gi0/0/0/0", "xrd28:Gi0/0/0/0"]
  - ["xrd27:Gi0/0/0/0", "xrd28:Gi0/0/0/1"]
  - ["xrd27:Gi0/0/0/1", "xrd29:Gi0/0/0/1"]
  - ["xrd28:Gi0/0/0/2", "xrd29:Gi0/0/0/0"]
  - ["xrd30:Gi0/0/0/2", "xrd26:Gi0/0/0/1"]
  - ["xrd30:Gi0/0/0/1", "xrd27:Gi0/0/0/2"]

networks:
  mgmt:
    xr_interfaces:
      - xrd27:Mg0/RP0/CPU0/0
      - xrd25:Mg0/RP0/CPU0/0
      - xrd26:Mg0/RP0/CPU0/0
      - xrd28:Mg0/RP0/CPU0/0
      - xrd29:Mg0/RP0/CPU0/0
      - xrd30:Mg0/RP0/CPU0/0
    ipam:
      config:
        - subnet: 172.40.0.0/24
  source-xrd25:
    ipam:
      config:
        - subnet: 10.0.25.0/24
    xr_interfaces:
      - xrd25:Gi0/0/0/2
  xrd26-host:
    ipam:
      config:
        - subnet: 10.10.26.0/24
    xr_interfaces:
      - xrd26:Gi0/0/0/3

  xrd27-host:
    ipam:
      config:
        - subnet: 10.10.27.0/24
    xr_interfaces:
      - xrd27:Gi0/0/0/3

  xrd29-host:
    ipam:
      config:
        - subnet: 10.10.29.0/24
    xr_interfaces:
      - xrd29:Gi0/0/0/2